# Numpy

NumPy stands for Numerical Python.

NumPy is a Python library used for working with arrays.

Using NumPy, mathematical and logical operations on arrays can be performed.

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

NumPy is often used along with packages like SciPy (Scientific Python) and Mat−plotlib (plotting library). 

In [1]:
import numpy as np

In [2]:
#help(np.array)

# Create a NumPy ndarray Object


NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5]) # using list
print(arr)

[1 2 3 4 5]


In [4]:
print(type(arr))# to find type

<class 'numpy.ndarray'>


To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [5]:
#using tuple
arr = np.array((1, 2, 3, 4, 5))
arr

array([1, 2, 3, 4, 5])

In [6]:
#arange()
#arange(start,stop,step)

In [7]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#zeros

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
#ones

In [12]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
#empty
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [14]:
np.empty([3,2],dtype = int)

array([[2025479872,        515],
       [         0,          0],
       [    131074,          0]])

#linspace()
numpy.linspace(start,
               stop,
               num = 50,
               endpoint = True,
               retstep = False,
               dtype = None)

-> start  : [optional] start of interval range. By default start = 0
-> stop   : end of interval range
-> restep : If True, return (samples, step). By default restep = False
-> num    : [int, optional] No. of samples to generate
-> dtype  : type of output array

In [15]:
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [16]:
np.linspace(1, 100, 10,endpoint=False)

array([ 1. , 10.9, 20.8, 30.7, 40.6, 50.5, 60.4, 70.3, 80.2, 90.1])

In [17]:
np.linspace(1, 100, 10,endpoint=False,retstep=True)

(array([ 1. , 10.9, 20.8, 30.7, 40.6, 50.5, 60.4, 70.3, 80.2, 90.1]), 9.9)

In [18]:
#eye
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
#random


In [20]:
#Generate a random integer from 0 to 100:

In [21]:
from numpy import random

x = random.randint(100)

print(x)

15


In [22]:
#he random module's rand() method returns a random float between 0 and 1.
from numpy import random

x = random.rand()

print(x)

0.10023845859548175


In [23]:


x=random.randint(100, size=(5))

print(x)

[83 65 83 12 92]


In [24]:


x = random.randint(100, size=(3, 5))

print(x)

[[ 3  4 59 81 10]
 [75 81  7  0 19]
 [98 45 85 34 37]]


In [25]:


x = random.rand(5)

print(x)

[0.53483692 0.35841563 0.71951916 0.0445178  0.41410237]


In [26]:
x = random.rand(5,3)
x

array([[0.09311668, 0.159406  , 0.04721179],
       [0.81986755, 0.02768733, 0.80762029],
       [0.5632742 , 0.19760361, 0.42871591],
       [0.54954952, 0.38777185, 0.28905574],
       [0.07940095, 0.00618145, 0.71327655]])

In [27]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Dimensions in Arrays

In [28]:
#0-D
arr = np.array(42)
arr

array(42)

In [29]:
#1D
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [30]:
#2-d
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr2.ndim

2

In [32]:
#3d
arr1 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arr1

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [33]:
arr1.ndim

3

In [34]:
#Check how many dimensions the arrays have:
#checking dimension
print(arr2.ndim)

2


# Creating Higher Dimensional Arrays

In [35]:
a= np.array([1, 2, 3, 4], ndmin=5)

In [36]:
a

array([[[[[1, 2, 3, 4]]]]])

In [37]:
a.ndim

5

In [38]:
# dtype parameter 
a1 = np.array([1, 2, 3], dtype = complex) 
a1

array([1.+0.j, 2.+0.j, 3.+0.j])

In [39]:
arr2.dtype

dtype('int32')

# Array attributes

In [40]:
a = np.array([[1,2,3],[4,5,6]]) 
a.shape

(2, 3)

In [41]:
a = np.array([[1,2,3],[4,5,6]]) 
a.shape = (3,2) 
a 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
a = np.array([[1,2,3],[4,5,6]]) 
a.ndim

2

In [43]:
xy= np.array([1,2,3,4,5])
xy.itemsize  #in bytes

4

In [44]:
x = np.array([1,2,3,4,5], dtype = np.int8) 
x.itemsize

1

In [45]:
x.size # no of elements in array

5

# Data types

In [46]:
x.dtype

dtype('int8')

In [47]:
xy.dtype

dtype('int32')

In [48]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [49]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [50]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [51]:
arr = np.array([1, 2, 3, 4], dtype='i4')
arr.dtype

dtype('int32')

In [52]:
#converting dtype
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [53]:
arr = np.array([1, 2, 3, 'apple'], dtype='O')

In [54]:
arr

array([1, 2, 3, 'apple'], dtype=object)

# indexing

In [55]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [56]:
a[0]

1

In [57]:
a[1]

2

In [58]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [59]:
arr[0,1]

2

In [60]:
a= np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
               [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
               [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])
a

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38]]])

In [61]:
(a[2, 0, 1])

31

In [62]:
#Access the element on the 2nd row, 5th column:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr[1,4]

10

In [63]:
#3d
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [64]:
arr[0, 1, 2]

6

In [65]:
#Negative Indexing

In [66]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr[1, -1]

10

# slicing

In [67]:
#Slice elements from index 1 to index 5 from the following array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [68]:
#Slice elements from index 4 to the end of the array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


In [69]:
#Slice elements from the beginning to index 4 (not included):
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[1 2 3 4]


In [70]:
#Negative Slicing
#Slice from the index 3 from the end to index 1 from the end:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


In [71]:
#Use the step value to determine the step of the slicing:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [72]:
#Return every other element from the entire array
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


In [73]:
#2d arrays

In [74]:
#From the second element, slice elements from index 1 to index 4 (not included):

In [75]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [76]:
#From both elements, return index 2:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


In [77]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [78]:
a= np.array([[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
               [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
               [[30, 31, 32], [33, 34, 35], [36, 37, 38]]])
a

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38]]])

In [79]:
a[:,:,:1]

array([[[10],
        [13],
        [16]],

       [[20],
        [23],
        [26]],

       [[30],
        [33],
        [36]]])

In [80]:
#arithemetic operation using scalar
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [81]:
#addition
a+2

array([3, 4, 5, 6])

In [82]:
a*2

array([2, 4, 6, 8])

In [83]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [84]:
a-1

array([0, 1, 2, 3])

In [85]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [86]:
a**3

array([ 1,  8, 27, 64], dtype=int32)

In [87]:
a%2

array([1, 0, 1, 0], dtype=int32)

In [88]:
#do the same for 2d

In [89]:
a=np.array([1,2,3,4])
b=np.array([10,20,30,40])

In [90]:
a+b

array([11, 22, 33, 44])

In [91]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
a+b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [94]:
p=np.array([1,2,3,4])
q=np.array([[1,2,3],[4,5,6]])

In [95]:
p+q

ValueError: operands could not be broadcast together with shapes (4,) (2,3) 

In [ ]:
#do the same for all operations

# broadcasting

Broadcasting is possible if the following rules are satisfied −

Array with smaller ndim than the other is prepended with '1' in its shape.

Size in each dimension of the output shape is maximum of the input sizes in that dimension.

An input can be used in calculation, if its size in a particular dimension matches the output size or its value is exactly 1.

If an input has a dimension size of 1, the first data entry in that dimension is used for all calculations along that dimension.

In [97]:
a=np.array([10,20,30])
b=np.array([1,2,3,4])
print(a)
print(b)

[10 20 30]
[1 2 3 4]


In [98]:
a+b

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [104]:
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([1,2,3])
c=np.array([10,20])

In [102]:
a.shape

(3, 2)

In [103]:
b.shape

(3,)

In [105]:
c.shape

(2,)

In [108]:
d=a+c #satisfies broadcasting rule
d

array([[11, 22],
       [13, 24],
       [15, 26]])

In [109]:
d.shape

(3, 2)

In [110]:
a+b #does not match broadcasting rule

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

# manipulation

In [120]:
#reshape
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [121]:
b = a.reshape(4,2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [129]:
#resize()
a=np.arange(5)
print(a)
np.resize(a,(2,3))

[0 1 2 3 4]


array([[0, 1, 2],
       [3, 4, 0]])

In [118]:
#flatten
import numpy as np 
a = np.arange(8).reshape(2,4) 

print ('The original array is:') 
print (a) 
print ('\n')  
# default is column-major 

print ('The flattened array is:')
print (a.flatten())
print ('\n')  

print ('The flattened array in F-style ordering:')
print (a.flatten(order = 'F'))

The original array is:
[[0 1 2 3]
 [4 5 6 7]]


The flattened array is:
[0 1 2 3 4 5 6 7]


The flattened array in F-style ordering:
[0 4 1 5 2 6 3 7]


In [130]:
#ravel()
a = np.arange(8).reshape(2,4) 
a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [133]:
#transpose
import numpy as np 
a = np.arange(12).reshape(3,4) 

print ('The original array is:')
print (a)  
print ('\n') 

print ('The transposed array is:') 
print (np.transpose(a))

The original array is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


The transposed array is:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [134]:
#swapaxes()
# It creates a 3 dimensional ndarray 
import numpy as np 
a = np.arange(8).reshape(2,2,2) 

print ('The original array:') 
print (a) 
print ('\n')  
# now swap numbers between axis 0 (along depth) and axis 2 (along width) 

print ('The array after applying the swapaxes function:') 
print (np.swapaxes(a, 2, 0))

The original array:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


The array after applying the swapaxes function:
[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


In [135]:
#concate
import numpy as np 
a = np.array([[1,2],[3,4]]) 

print ('First array:') 
print (a) 
print ('\n')  
b = np.array([[5,6],[7,8]]) 

print ('Second array:') 
print (b) 
print ('\n')  
# both the arrays are of same dimensions 

print ('Joining the two arrays along axis 0:') 
print (np.concatenate((a,b))) 
print ('\n') 

print ('Joining the two arrays along axis 1:') 
print (np.concatenate((a,b),axis = 1))

First array:
[[1 2]
 [3 4]]


Second array:
[[5 6]
 [7 8]]


Joining the two arrays along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Joining the two arrays along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


In [136]:
#h stack
import numpy as np 
a = np.array([[1,2],[3,4]]) 

print ('First array:') 
print (a) 
print ('\n')  
b = np.array([[5,6],[7,8]]) 

print ('Second array:') 
print (b) 
print ('\n')  

print ('Horizontal stacking:') 
c = np.hstack((a,b)) 
print (c) 
print ('\n')

First array:
[[1 2]
 [3 4]]


Second array:
[[5 6]
 [7 8]]


Horizontal stacking:
[[1 2 5 6]
 [3 4 7 8]]




In [137]:
#vstack()
import numpy as np 
a = np.array([[1,2],[3,4]]) 

print ('First array:') 
print (a)
print ('\n')  
b = np.array([[5,6],[7,8]]) 

print ('Second array:') 
print (b) 
print ('\n')

print ('Vertical stacking:') 
c = np.vstack((a,b)) 
print (c)

First array:
[[1 2]
 [3 4]]


Second array:
[[5 6]
 [7 8]]


Vertical stacking:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [138]:
#split
import numpy as np 
a = np.arange(9) 

print ('First array:') 
print (a) 
print ('\n')  

print ('Split the array in 3 equal-sized subarrays:') 
b = np.split(a,3) 
print (b )
print ('\n')  

print ('Split the array at positions indicated in 1-D array:') 
b = np.split(a,[4,7])
print(b) 

First array:
[0 1 2 3 4 5 6 7 8]


Split the array in 3 equal-sized subarrays:
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


Split the array at positions indicated in 1-D array:
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [139]:
#hsplit
import numpy as np 
a = np.arange(16).reshape(4,4) 

print ('First array:') 
print (a) 
print ('\n')  

print ('Horizontal splitting:') 
b = np.hsplit(a,2) 
print (b) 
print ('\n')

First array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Horizontal splitting:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]




In [141]:
#vsplit
import numpy as np 
a = np.arange(16).reshape(4,4) 

print ('First array:') 
print (a) 
print ('\n')

print ('Vertical splitting:') 
b = np.vsplit(a,2) 
print (b)

First array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Vertical splitting:
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [142]:
#insert
import numpy as np 
a = np.array([[1,2],[3,4],[5,6]]) 

print ('First array:') 
print (a) 
print ('\n')  

print ('Axis parameter not passed. The input array is flattened before insertion.')
print (np.insert(a,3,[11,12])) 
print ('\n')  
print ('Axis parameter passed. The values array is broadcast to match input array.')

print ('Broadcast along axis 0:') 
print (np.insert(a,1,[11],axis = 0)) 
print ('\n')  

print ('Broadcast along axis 1:') 
print (np.insert(a,1,11,axis = 1))

First array:
[[1 2]
 [3 4]
 [5 6]]


Axis parameter not passed. The input array is flattened before insertion.
[ 1  2  3 11 12  4  5  6]


Axis parameter passed. The values array is broadcast to match input array.
Broadcast along axis 0:
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


Broadcast along axis 1:
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


In [143]:
#append
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 

print ('First array:') 
print (a) 
print ('\n')  

print ('Append elements to array:') 
print (np.append(a, [7,8,9]))
print ('\n')  

print ('Append elements along axis 0:') 
print (np.append(a, [[7,8,9]],axis = 0)) 
print ('\n')  

print ('Append elements along axis 1:') 
print (np.append(a, [[5,5,5],[7,8,9]],axis = 1))

First array:
[[1 2 3]
 [4 5 6]]


Append elements to array:
[1 2 3 4 5 6 7 8 9]


Append elements along axis 0:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Append elements along axis 1:
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [144]:
#delete
import numpy as np 
a = np.arange(12).reshape(3,4) 

print ('First array:') 
print (a) 
print ('\n')  

print ('Array flattened before delete operation as axis not used:') 
print (np.delete(a,5)) 
print ('\n')  

print ('Column 2 deleted:')  
print (np.delete(a,1,axis = 1) )
print ('\n')  

print ('A slice containing alternate values from array deleted:' )
a = np.array([1,2,3,4,5,6,7,8,9,10]) 
print (np.delete(a, np.s_[::2]))

First array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Array flattened before delete operation as axis not used:
[ 0  1  2  3  4  6  7  8  9 10 11]


Column 2 deleted:
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


A slice containing alternate values from array deleted:
[ 2  4  6  8 10]


# Matrices

In [155]:
#creating matrix
a=np.matrix("1 2;3 4")
a

matrix([[1, 2],
        [3, 4]])

In [148]:
#from list
b=np.matrix([[10,20],[30,40]])
b

matrix([[10, 20],
        [30, 40]])

In [149]:
#addition
a+b

matrix([[11, 22],
        [33, 44]])

In [150]:
#multiplication
a*b

matrix([[ 70, 100],
        [150, 220]])

In [151]:
#transpose
a.T

matrix([[1, 3],
        [2, 4]])

In [156]:
np.linalg.inv(a)

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [157]:
np.linalg.matrix_power(a,2)

matrix([[ 7, 10],
        [15, 22]])